# Generated by Django 2.2.16 on 2020-10-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(max_length=500)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
            ],
        ),
    ]
